hotkeys:
  toggle-window: []
  copy-current-path: []
  ctrl-c:
    - Ctrl-C
  copy:
    - Ctrl-Shift-C
  paste:
    - Ctrl-Shift-V
    - Shift-Insert
  select-all:
    - Ctrl-Shift-A
  zoom-in:
    - Ctrl-=
    - Ctrl-Shift-=
  zoom-out:
    - Ctrl--
    - Ctrl-Shift--
  reset-zoom:
    - Ctrl-0
  home:
    - Home
  end:
    - End
  previous-word:
    - Ctrl-Left
  next-word:
    - Ctrl-Right
  delete-previous-word: []
  delete-line: []
  delete-next-word: []
  search:
    - Ctrl-Shift-F
  pane-focus-all:
    - Ctrl-Shift-I
  focus-all-tabs:
    - Ctrl-Alt-Shift-I
  scroll-to-top:
    - Ctrl-PageUp
  scroll-up:
    - Alt-PageUp
  scroll-down:
    - Alt-PageDown
  scroll-to-bottom:
    - Ctrl-PageDown
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings-tab:
    hotkeys:
      - Ctrl-Shift-Q
  settings:
    - Ctrl-,
  serial: []
  restart-serial-session: []
  new-window:
    - Ctrl-Shift-N
  profile:
    local:custom:WSL-Ubuntu-20-04:31490303-5f24-48a8-be5b-621a1eaffa15:
      - Ctrl-Shift-T
  profile-selectors: {}
  toggle-fullscreen:
    - F11
    - Alt-Enter
  close-tab:
    - Ctrl-Shift-W
  reopen-tab:
    - Ctrl-Shift-Z
  toggle-last-tab: []
  rename-tab:
    - Ctrl-Shift-R
  next-tab:
    - Ctrl-Shift-Right
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Left
    - Ctrl-Shift-Tab
  move-tab-left:
    - Ctrl-Shift-PageUp
  move-tab-right:
    - Ctrl-Shift-PageDown
  rearrange-panes:
    - Ctrl-Shift
  duplicate-tab: []
  restart-tab: []
  reconnect-tab: []
  disconnect-tab: []
  explode-tab:
    - Ctrl-Shift-.
  combine-tabs:
    - Ctrl-Shift-,
  tab-1: []
  tab-2: []
  tab-3: []
  tab-4:
    - Alt-4
  tab-5:
    - Alt-5
  tab-6:
    - Alt-6
  tab-7:
    - Alt-7
  tab-8:
    - Alt-8
  tab-9:
    - Alt-9
  tab-10:
    - Alt-0
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - Alt-Shift-D
  split-left: []
  split-top: []
  pane-nav-down:
    - Ctrl-Alt-Down
  pane-nav-next:
    - Ctrl-Alt-]
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  pane-maximize:
    - Ctrl-Alt-Enter
  close-pane:
    - Alt-Shift-W
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  switch-profile:
    - Ctrl-Alt-T
  profile-selector:
    - Ctrl-Shift-E
  command-selector:
    - Ctrl-Shift-P
  split-bottom:
    - Ctrl-Shift-D
  clear:
    - Ctrl-K
  pane-nav-previous:
    - Ctrl-Alt-[
  pane-nav-left:
    - Ctrl-Alt-Left
  pane-nav-right:
    - Ctrl-Alt-Right
  search-in-browser:
    - Ctrl-Shift-S
  qc:
    - Alt-Q
  pane-nav-up:
    - Ctrl-Alt-Up
  new-tab:
    - Ctrl-Shift-T
terminal:
  frontend: xterm-webgl
  fontWeightBold: 700
  fallbackFont: null
  linePadding: 1
  bell: 'off'
  bracketedPaste: true
  background: theme
  ligatures: true
  cursor: beam
  cursorBlink: true
  hideTabIndex: false
  showTabProfileIcon: false
  hideCloseButton: false
  hideTabOptionsButton: false
  rightClick: clipboard
  pasteOnMiddleClick: true
  copyOnSelect: true
  copyAsHTML: true
  scrollOnInput: true
  altIsMeta: false
  wordSeparator: ' ()[]{}''"'
  colorScheme:
    name: Base16 Default Dark
    foreground: '#ffffff'
    background: '#181818'
    cursor: '#d8d8d8'
    colors:
      - '#181818'
      - '#ab4642'
      - '#a1b56c'
      - '#f7ca88'
      - '#7cafc2'
      - '#ba8baf'
      - '#86c1b9'
      - '#d8d8d8'
      - '#585858'
      - '#ab4642'
      - '#a1b56c'
      - '#f7ca88'
      - '#7cafc2'
      - '#ba8baf'
      - '#86c1b9'
      - '#f8f8f8'
      - '#dc9656'
      - '#a16946'
      - '#282828'
      - '#383838'
      - '#b8b8b8'
      - '#e8e8e8'
  lightColorScheme:
    name: Tabby Default Light
    foreground: '#4d4d4c'
    background: '#ffffff'
    cursor: '#4d4d4c'
    colors:
      - '#000000'
      - '#c82829'
      - '#718c00'
      - '#eab700'
      - '#4271ae'
      - '#8959a8'
      - '#3e999f'
      - '#ffffff'
      - '#000000'
      - '#c82829'
      - '#718c00'
      - '#eab700'
      - '#4271ae'
      - '#8959a8'
      - '#3e999f'
      - '#ffffff'
  customColorSchemes: []
  warnOnMultilinePaste: true
  searchRegexAlwaysEnabled: false
  searchOptions:
    regex: false
    wholeWord: false
    caseSensitive: false
  detectProgress: true
  scrollbackLines: 25000
  drawBoldTextInBrightColors: true
  sixel: true
  trimWhitespaceOnPaste: true
  font: MesloLGLDZ Nerd Font Mono
  autoOpen: true
  useConPTY: true
  environment: {}
  setComSpec: false
  profile: local:default
  showBuiltinProfiles: true
  showRecentProfiles: 3
  paneResizeStep: 0.1
  focusFollowsMouse: true
  identification: null
  fontSize: 13
  fontWeight: 500
ssh:
  warnOnClose: false
  winSCPPath: null
  agentType: auto
  agentPath: null
  x11Display: null
  knownHosts:
    - host: 153.127.63.174
      port: 22
      type: ecdsa-sha2-nistp256
      digest: mQrodKeM4/IghoHUIQvzx0IPQYL1HV/6oYkO1SqNsMs=
    - host: 3.112.126.56
      port: 22
      type: ecdsa-sha2-nistp256
      digest: Xz7TsHP0InZ6Xm3D9skvqoG2XmLanOMLOULqsYYYGm8=
    - host: 18.181.164.129
      port: 22
      type: ecdsa-sha2-nistp256
      digest: 0Ux27vzsa4n+QqA77IItOr+tbaJFVvVzd/XAA94lq6s=
    - host: 35.79.7.83
      port: 22
      type: ecdsa-sha2-nistp256
      digest: Xz7TsHP0InZ6Xm3D9skvqoG2XmLanOMLOULqsYYYGm8=
    - host: 57.180.87.161
      port: 22
      type: ecdsa-sha2-nistp256
      digest: RqAHZ7MMytQtED/kvh9olEm8BFVm1WferfXtYMuv6o4=
  verifyHostKeys: true
configSync:
  configID: null
  auto: false
  parts:
    hotkeys: true
    appearance: true
    vault: true
clickableLinks:
  modifier: ctrlKey
accessibility:
  animations: true
appearance:
  dockScreen: current
  dockFill: 0.5
  dockSpace: 1
  dockHideOnBlur: false
  dockAlwaysOnTop: true
  flexTabs: false
  tabsLocation: top
  tabsInFullscreen: false
  cycleTabs: true
  css: '/* * { color: blue !important; } */'
  vibrancyType: blur
  lastTabClosesWindow: false
  colorSchemeMode: dark
  spaciness: 0.8
  opacity: 0.47
  vibrancy: true
profiles: []
groups: []
profileDefaults:
  ssh:
    disableDynamicTitle: true
recoverTabs: true
enableAnalytics: true
enableWelcomeTab: false
electronFlags:
  - - force_discrete_gpu
    - '0'
enableAutomaticUpdates: true
hideTray: false
version: 7
vault: null
encrypted: false
enableExperimentalFeatures: false
commandBlacklist: []
providerBlacklist: []
profileBlacklist:
  - local:usrbinbash
  - local:bindash
  - local:usrbindash
  - socket:template
  - local:binrbash
  - local:usrbinrbash
  - local:binsh
  - local:usrbinsh
  - serial:port-devttyS1
  - serial:port-devttyS10
  - serial:port-devttyS11
  - serial:port-devttyS12
  - serial:port-devttyS13
  - serial:port-devttyS14
  - serial:port-devttyS15
  - serial:port-devttyS16
  - serial:port-devttyS17
  - serial:port-devttyS18
  - serial:port-devttyS19
  - serial:port-devttyS2
  - serial:port-devttyS20
  - serial:port-devttyS21
  - serial:port-devttyS22
  - serial:port-devttyS23
  - serial:port-devttyS24
  - serial:port-devttyS25
  - serial:port-devttyS26
  - serial:port-devttyS27
  - serial:port-devttyS28
  - serial:port-devttyS29
  - serial:port-devttyS3
  - serial:port-devttyS30
  - serial:port-devttyS31
  - serial:port-devttyS4
  - serial:port-devttyS5
  - serial:port-devttyS6
  - serial:port-devttyS7
  - serial:port-devttyS8
  - serial:port-devttyS9
  - serial:port-devttyS0
  - serial:template
  - local:default
hacks:
  disableGPU: false
  disableVibrancyWhileDragging: false
  enableFluentBackground: false
language: ja-JP
defaultQuickConnectProvider: ssh
pluginBlacklist: []
